/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseEmpty: typeof import('./src/components/base/BaseEmpty.vue')['default']
    JsChart: typeof import('./src/components/base/JsChart.vue')['default']
    ProductCard: typeof import('./src/components/business/product/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonLoader: typeof import('./src/components/base/SkeletonLoader.vue')['default']
    TsChart: typeof import('./src/components/base/TsChart.vue')['default']
    VirtualList: typeof import('./src/components/base/VirtualList.vue')['default']
  }
}
